export const list = [
	{
		id: 1,
		name: "Red Carpet Real Estate",
		address: "210 Zirak Road, Canada",
		category: "For Rent",
		location: "canada",
		cover: "../assets/p-1.png",
		price: "3700",
		type: "Apartment",
		beds: "4",
		bathrooms: "2",
		available_from: "2022-11-01",
		area: "5*7",
	},
	{
		id: 2,
		name: "Fairmount Properties",
		address: "5698 Zirak Road, NewYork",
		category: "For Sale",
		location: "newyork",
		cover: "../assets/p-2.png",
		price: "9750",
		type: "Condos",
		beds: "5",
		bathrooms: "4",
		available_from: "2022-11-30",
		area: "10*15",
	},
	{
		id: 3,
		name: "The Real Estate Corner",
		address: "5624 Mooker Market, USA",
		category: "For Rent",
		location: "usa",
		cover: "../assets/p-4.png",
		price: "5860",
		type: "Offices",
		beds: "1",
		bathrooms: "2",
		available_from: "2022-10-11",
		area: "9*7",
	},
	{
		id: 4,
		name: "Herringbone Realty",
		address: "5621 Liverpool, London",
		category: "For Sale",
		location: "london",
		cover: "../assets/p-5.png",
		price: "7540",
		type: "Houses",
		beds: "4",
		bathrooms: "2",
		available_from: "2022-09-30",
		area: "20*40",
	},
	{
		id: 5,
		name: "Brick Lane Realty",
		address: "210 Montreal Road, Canada",
		category: "For Rent",
		location: "canada",
		cover: "../assets/p-6.png",
		price: "4850",
		type: "Commercial",
		beds: "1",
		bathrooms: "5",
		available_from: "2022-12-01",
		area: "40*80",
	},
	{
		id: 6,
		name: "Banyon Tree Realty",
		address: "210 Zirak Road, Canada",
		category: "For Sale",
		location: "canada",
		cover: "../assets/p-7.png",
		price: "2742",
		type: "Apartment",
		beds: "2",
		bathrooms: "2",
		available_from: "2022-10-21",
		area: "15*8",
	},
	{
		id: 7,
		name: "4 bed terraced house to rent",
		address: "Henry Road, Oxford OX2",
		category: "For Rent",
		location: "oxford",
		cover: "../assets/p-8.jpg",
		price: "531",
		type: "Apartment",
		beds: "4",
		bathrooms: "2",
		available_from: "2022-10-21",
		area: "10*11",
	},
	{
		id: 8,
		name: "2 bed flat to rent",
		address: "Binsey Lane, Oxford",
		category: "For Sale",
		location: "oxford",
		cover: "../assets/p-9.jpg",
		price: "381",
		type: "Condos",
		beds: "2",
		bathrooms: "1",
		available_from: "2022-11-30",
		area: "20*35",
	},
	{
		id: 9,
		name: "Flat to rent",
		address: "5621 Liverpool, London",
		category: "For rent",
		location: "london",
		cover: "../assets/p-10.jpg",
		price: "277",
		type: "Offices",
		beds: "2",
		bathrooms: "2",
		available_from: "2022-10-11",
		area: "18*18",
	},
	{
		id: 10,
		cover: "../assets/p-11.jpg",
		name: "Fairmount Corner",
		address: "5621 Liverpool, London",
		location: "london",
		category: "For sale",
		price: "2400",
		type: "Houses",
		beds: "4",
		bathrooms: "4",
		available_from: "2022-09-30",
		area: "80*80",
	},
	{
		id: 11,
		cover: "../assets/p-12.jpg",
		name: "College & County Ltd",
		address: "Disney Lane, Oxford",
		location: "oxford",
		category: "For sale",
		price: "3500",
		type: "Commercial",
		beds: "1",
		bathrooms: "2",
		available_from: "2022-11-27",
		area: "100*50",
	},
	{
		id: 12,
		cover: "../assets/p-13.jpg",
		name: "Black Carpet Real Estate",
		address: "10 Zirak Road, Canada",
		location: "canada",
		category: "For rent",
		price: "4500",
		type: "Apartment",
		beds: "4",
		bathrooms: "4",
		available_from: "2022-09-30",
		area: "50*50",
	},
];
